Repository fbdevelopercircles/open-source-edu-bot, pull requests merged in 2020-08, with the labels that each got.

#71 fix: ModuleNotFoundError : no module named 'fbosbot'
  .github/workflows/main.yml
  .github/workflows/pr.yml
  README.md
  src/.sample.env
Labels: CLA Signed

#72 fix ENV file locations and update Hindi alignment
  src/.sample.env
  src/locales/fr/LC_MESSAGES/messages.po
  src/locales/hi/LC_MESSAGES/messages.po
Labels: CLA Signed, enhancement

#74 Updating Hindi locale hi_HI => hi_IN
  src/services/profile.py
Labels: CLA Signed, enhancement

#76 Spelling error fix :Updated spelling error from "bellow" to "below" in profile.py
  src/services/messenger.py
  src/services/profile.py
Labels: CLA Signed

#78 Add How to Contribute Guide and Format Markdown Syntax
  README.md
Labels: CLA Signed

#79 contributors.yaml updated
  contributors.yaml
Labels: CLA Signed

#82 Update contributors.yaml
  contributors.yaml
Labels: CLA Signed

#83 Revert "Update contributors.yaml"
  contributors.yaml
Labels: CLA Signed

#81 Update Contributors.yaml
  contributors.yaml
Labels: CLA Signed

#84 Update contributors.yaml
  contributors.yaml
Labels: CLA Signed

#86 add aayushbisen as contributor
  contributors.yaml
Labels: CLA Signed

#85 Update Contributing.md
  CONTRIBUTING.md
Labels: CLA Signed

#88 Added Sinhala Language Support (si) (si LK)
  contributors.yaml
  src/locales/si/LC_MESSAGES/messages.po
  src/services/profile.py
Labels: CLA Signed

#90 Update messages.po with FB License notice
  src/locales/si/LC_MESSAGES/messages.po
Labels: CLA Signed

#87 improved some hindi translations
  src/locales/hi/LC_MESSAGES/messages.po
  src/services/profile.py
Labels: CLA Signed

#89 Add Contributing Guide
  README.md
Labels: CLA Signed

#93 fix: added getting started docs
  README.md
Labels: CLA Signed

#94 Update links in 2 files
  CONTRIBUTING.md
  README.md
Labels: CLA Signed

#97 fix: removed full-stops after emojis
  src/locales/fr/LC_MESSAGES/messages.po
  src/locales/hi/LC_MESSAGES/messages.po
  src/locales/si/LC_MESSAGES/messages.po
  src/services/messenger.py
Labels: CLA Signed

#100 Add myself to contributors
  contributors.yaml
Labels: CLA Signed

#99 adds Kinyarwanda language support
  src/locales/rw/LC_MESSAGES/messages.po
  src/services/profile.py
Labels: CLA Signed

#101 fix: modified setup in Readme.md
  README.md
Labels: CLA Signed

#104 #103 Ikinyarwanda correction + translations alignment
  src/locales/fr/LC_MESSAGES/messages.po
  src/locales/hi/LC_MESSAGES/messages.po
  src/locales/rw/LC_MESSAGES/messages.po
  src/locales/si/LC_MESSAGES/messages.po
  src/services/profile.py
Labels: CLA Signed, enhancement

#105 Removing unecessary space in translatable a texte
  src/locales/fr/LC_MESSAGES/messages.po
  src/locales/hi/LC_MESSAGES/messages.po
  src/locales/rw/LC_MESSAGES/messages.po
  src/locales/si/LC_MESSAGES/messages.po
  src/services/messenger.py
Labels: CLA Signed

#108 Added my info to the contributors list
  contributors.yaml
Labels: CLA Signed

#111 Updated Readme & resolved typo mistake.
  README.md
Labels: CLA Signed

#115 Updated src/services/messenger.py
  src/services/messenger.py
Labels: CLA Signed

#118 Added my details to the list contributors.yaml
  contributors.yaml
Labels: CLA Signed

#117 Bot replies fixes in src/services/messenger.py
  src/services/messenger.py
Labels: CLA Signed

#112 Add Gujarati language translation!
  src/locales/gu/LC_MESSAGES/messages.po
  src/services/profile.py
Labels: CLA Signed, help wanted

#119 Added name to contributors
  contributors.yaml
Labels: CLA Signed

#116 Arabic translation
  src/locales/ar/LC_MESSAGES/messages.po
  src/services/profile.py
Labels: CLA Signed

#121 Translations alignement !
  src/locales/ar/LC_MESSAGES/messages.po
  src/locales/fr/LC_MESSAGES/messages.po
  src/locales/gu/LC_MESSAGES/messages.po
  src/locales/hi/LC_MESSAGES/messages.po
  src/locales/rw/LC_MESSAGES/messages.po
  src/locales/si/LC_MESSAGES/messages.po
  src/services/messenger.py
Labels: CLA Signed

#120 Add RITIK to the contributors.yaml
  contributors.yaml
Labels: CLA Signed

#127 Simpliflying installation process in README.md
  README.md
  contributors.yaml
Labels: CLA Signed
